ROLE_BRANCH_EMPLOYEE = "Awamir Branch Employee"
ROLE_BRANCH_SUPERVISOR = "Awamir Branch Supervisor"
ROLE_DISTRIBUTION_MANAGER = "Awamir Distribution Manager"
ROLE_PRODUCTION_USER = "Awamir Production User"
ROLE_DRIVER = "Awamir Driver"
ROLE_CASHIER = "Awamir Cashier"
ROLE_ACCOUNTANT = "Awamir Accountant"
ROLE_SYSTEM_ADMIN = "Awamir System Admin"

AWAMIR_ROLES = [
    ROLE_BRANCH_EMPLOYEE,
    ROLE_BRANCH_SUPERVISOR,
    ROLE_DISTRIBUTION_MANAGER,
    ROLE_PRODUCTION_USER,
    ROLE_DRIVER,
    ROLE_CASHIER,
    ROLE_ACCOUNTANT,
    ROLE_SYSTEM_ADMIN,
]

ORDER_STATUS_DRAFT = "Draft"
ORDER_STATUS_PENDING_APPROVAL = "Pending Supervisor Approval"
ORDER_STATUS_RETURNED = "Returned For Edit"
ORDER_STATUS_REJECTED = "Rejected"
ORDER_STATUS_SENT_TO_DISTRIBUTION = "Sent To Distribution"
ORDER_STATUS_SENT_TO_PRODUCTION = "Sent To Production"
ORDER_STATUS_IN_PRODUCTION = "In Production"
ORDER_STATUS_PRODUCTION_COMPLETED = "Production Completed"
ORDER_STATUS_READY_FOR_PICKUP = "Ready For Pickup"
ORDER_STATUS_READY_FOR_DELIVERY = "Ready For Delivery"
ORDER_STATUS_ASSIGNED_TO_DRIVER = "Assigned To Driver"
ORDER_STATUS_DRIVER_PICKED_UP = "Driver Picked Up"
ORDER_STATUS_OUT_FOR_DELIVERY = "Out For Delivery"
ORDER_STATUS_DELIVERED = "Delivered"
ORDER_STATUS_DELIVERY_FAILED = "Delivery Failed"
ORDER_STATUS_CANCELLED = "Cancelled"

ORDER_STATUSES = [
    ORDER_STATUS_DRAFT,
    ORDER_STATUS_PENDING_APPROVAL,
    ORDER_STATUS_RETURNED,
    ORDER_STATUS_REJECTED,
    ORDER_STATUS_SENT_TO_DISTRIBUTION,
    ORDER_STATUS_SENT_TO_PRODUCTION,
    ORDER_STATUS_IN_PRODUCTION,
    ORDER_STATUS_PRODUCTION_COMPLETED,
    ORDER_STATUS_READY_FOR_PICKUP,
    ORDER_STATUS_READY_FOR_DELIVERY,
    ORDER_STATUS_ASSIGNED_TO_DRIVER,
    ORDER_STATUS_DRIVER_PICKED_UP,
    ORDER_STATUS_OUT_FOR_DELIVERY,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_DELIVERY_FAILED,
    ORDER_STATUS_CANCELLED,
]

PAYMENT_STATUS_RECORDED = "Recorded By Employee"
PAYMENT_STATUS_IN_DAILY_CLOSURE = "In Daily Closure"
PAYMENT_STATUS_SUBMITTED = "Submitted To Cashier"
PAYMENT_STATUS_RETURNED = "Returned For Review"
PAYMENT_STATUS_CASHIER_ACCEPTED = "Cashier Accepted"
PAYMENT_STATUS_READY_FOR_ERP = "Ready For ERPNext Posting"
PAYMENT_STATUS_POSTED_TO_ERP = "Posted To ERPNext"
PAYMENT_STATUS_LINKED_TO_INVOICE = "Linked To Invoice"

PAYMENT_STATUSES = [
    PAYMENT_STATUS_RECORDED,
    PAYMENT_STATUS_IN_DAILY_CLOSURE,
    PAYMENT_STATUS_SUBMITTED,
    PAYMENT_STATUS_RETURNED,
    PAYMENT_STATUS_CASHIER_ACCEPTED,
    PAYMENT_STATUS_READY_FOR_ERP,
    PAYMENT_STATUS_POSTED_TO_ERP,
    PAYMENT_STATUS_LINKED_TO_INVOICE,
]

CLOSURE_STATUS_OPEN = "Open"
CLOSURE_STATUS_SUBMITTED = "Submitted To Cashier"
CLOSURE_STATUS_RETURNED = "Returned For Review"
CLOSURE_STATUS_ACCEPTED = "Accepted"
CLOSURE_STATUS_CLOSED = "Closed"
CLOSURE_STATUS_HAS_DIFFERENCE = "Has Difference"

CLOSURE_STATUSES = [
    CLOSURE_STATUS_OPEN,
    CLOSURE_STATUS_SUBMITTED,
    CLOSURE_STATUS_RETURNED,
    CLOSURE_STATUS_ACCEPTED,
    CLOSURE_STATUS_CLOSED,
    CLOSURE_STATUS_HAS_DIFFERENCE,
]

ERP_SYNC_NOT_SYNCED = "Not Synced"
ERP_SYNC_PENDING = "Pending"
ERP_SYNC_SYNCED = "Synced"
ERP_SYNC_FAILED = "Failed"
ERP_SYNC_PARTIALLY_SYNCED = "Partially Synced"

ERP_SYNC_STATUSES = [
    ERP_SYNC_NOT_SYNCED,
    ERP_SYNC_PENDING,
    ERP_SYNC_SYNCED,
    ERP_SYNC_FAILED,
    ERP_SYNC_PARTIALLY_SYNCED,
]

