ROLE_BRANCH_EMPLOYEE = "Awamir Branch Employee"
ROLE_BRANCH_SUPERVISOR = "Awamir Branch Supervisor"
ROLE_DISTRIBUTION_MANAGER = "Awamir Distribution Manager"
ROLE_PRODUCTION_USER = "Awamir Production User"
ROLE_DRIVER = "Awamir Driver"
ROLE_CASHIER = "Awamir Cashier"
ROLE_ACCOUNTANT = "Awamir Accountant"
ROLE_SYSTEM_ADMIN = "Awamir System Admin"

SEMANTIC_ROLE_BRANCH_OPERATOR = "branch_operator"
SEMANTIC_ROLE_BRANCH_SUPERVISOR = "branch_supervisor"
SEMANTIC_ROLE_FULFILLMENT_COORDINATOR = "fulfillment_coordinator"
SEMANTIC_ROLE_PRODUCTION_OPERATOR = "production_operator"
SEMANTIC_ROLE_DRIVER = "driver"
SEMANTIC_ROLE_CASHIER = "cashier"
SEMANTIC_ROLE_ACCOUNTANT = "accountant"
SEMANTIC_ROLE_PLATFORM_ADMIN = "platform_admin"

LEGACY_ROLE_TO_SEMANTIC_ROLE = {
    ROLE_BRANCH_EMPLOYEE: SEMANTIC_ROLE_BRANCH_OPERATOR,
    ROLE_BRANCH_SUPERVISOR: SEMANTIC_ROLE_BRANCH_SUPERVISOR,
    ROLE_DISTRIBUTION_MANAGER: SEMANTIC_ROLE_FULFILLMENT_COORDINATOR,
    ROLE_PRODUCTION_USER: SEMANTIC_ROLE_PRODUCTION_OPERATOR,
    ROLE_DRIVER: SEMANTIC_ROLE_DRIVER,
    ROLE_CASHIER: SEMANTIC_ROLE_CASHIER,
    ROLE_ACCOUNTANT: SEMANTIC_ROLE_ACCOUNTANT,
    ROLE_SYSTEM_ADMIN: SEMANTIC_ROLE_PLATFORM_ADMIN,
}

AWAMIR_ROLES = [
    ROLE_BRANCH_EMPLOYEE,
    ROLE_BRANCH_SUPERVISOR,
    ROLE_DISTRIBUTION_MANAGER,
    ROLE_PRODUCTION_USER,
    ROLE_DRIVER,
    ROLE_CASHIER,
    ROLE_ACCOUNTANT,
    ROLE_SYSTEM_ADMIN,
]

PERMISSION_ORDER_CREATE = "order.create"
PERMISSION_ORDER_VIEW_OWN = "order.view_own"
PERMISSION_ORDER_VIEW_BRANCH = "order.view_branch"
PERMISSION_ORDER_EDIT_DRAFT = "order.edit_draft"
PERMISSION_ORDER_CANCEL = "order.cancel"
PERMISSION_ORDER_APPROVE = "order.approve"
PERMISSION_ORDER_REJECT = "order.reject"
PERMISSION_ORDER_RETURN_FOR_EDIT = "order.return_for_edit"
PERMISSION_ORDER_DELIVER_BRANCH = "order.deliver_branch"
PERMISSION_FULFILLMENT_VIEW_QUEUE = "fulfillment.view_queue"
PERMISSION_FULFILLMENT_CREATE = "fulfillment.create"
PERMISSION_FULFILLMENT_SPLIT_BY_DEPARTMENT = "fulfillment.split_by_department"
PERMISSION_FULFILLMENT_CREATE_WORK_ORDERS = "fulfillment.create_department_work_orders"
PERMISSION_FULFILLMENT_ASSIGN_DEPARTMENT = "fulfillment.assign_department"
PERMISSION_FULFILLMENT_VIEW_DEPARTMENT_STATUS = "fulfillment.view_department_status"
PERMISSION_WORK_ORDER_VIEW_DEPARTMENT = "work_order.view_department"
PERMISSION_WORK_ORDER_ACCEPT = "work_order.accept"
PERMISSION_WORK_ORDER_REJECT = "work_order.reject"
PERMISSION_WORK_ORDER_UPDATE_STATUS = "work_order.update_status"
PERMISSION_PRODUCTION_MARK_READY = "production.mark_ready"
PERMISSION_DELIVERY_BATCH_CREATE = "delivery_batch.create"
PERMISSION_DELIVERY_BATCH_ASSIGN_DRIVER = "delivery_batch.assign_driver"
PERMISSION_DELIVERY_BATCH_VIEW = "delivery_batch.view"
PERMISSION_DELIVERY_BATCH_VIEW_ASSIGNED = "delivery_batch.view_assigned"
PERMISSION_DELIVERY_BATCH_UPDATE_STATUS = "delivery_batch.update_status"
PERMISSION_DELIVERY_VIEW_ALL = "delivery.view_all"
PERMISSION_DELIVERY_VIEW_ASSIGNED = "delivery.view_assigned"
PERMISSION_DELIVERY_UPDATE_STATUS = "delivery.update_status"
PERMISSION_DELIVERY_CONFIRM_DELIVERED = "delivery.confirm_delivered"
PERMISSION_DELIVERY_COLLECT_CASH = "delivery.collect_cash"
PERMISSION_PAYMENT_COLLECT_BRANCH = "payment.collect_branch"
PERMISSION_CASHBOX_VIEW_OWN = "cashbox.view_own"
PERMISSION_CASHBOX_VIEW_ALL = "cashbox.view_all"
PERMISSION_CASHBOX_REVIEW = "cashbox.review"
PERMISSION_CASHBOX_APPROVE = "cashbox.approve"
PERMISSION_CASHBOX_RETURN = "cashbox.return"
PERMISSION_CASHBOX_CLOSE_DAY = "cashbox.close_day"
PERMISSION_ACCOUNTING_VIEW_FINANCIALS = "accounting.view_financials"
PERMISSION_ACCOUNTING_REVIEW_INVOICE = "accounting.review_invoice"
PERMISSION_ACCOUNTING_SUBMIT_INVOICE = "accounting.submit_invoice"
PERMISSION_ACCOUNTING_REVIEW_PAYMENT = "accounting.review_payment"
PERMISSION_ACCOUNTING_SUBMIT_PAYMENT = "accounting.submit_payment"
PERMISSION_ACCOUNTING_RECONCILE_PAYMENTS = "accounting.reconcile_payments"
PERMISSION_ACCOUNTING_VIEW_REPORTS = "accounting.view_reports"
PERMISSION_ACCOUNTING_CLOSE_FINANCIAL_DAY = "accounting.close_financial_day"
PERMISSION_ADMIN_MANAGE_USERS = "admin.manage_users"
PERMISSION_ADMIN_MANAGE_ROLES = "admin.manage_roles"
PERMISSION_ADMIN_MANAGE_PERMISSIONS = "admin.manage_permissions"
PERMISSION_ADMIN_MANAGE_BRANCHES = "admin.manage_branches"
PERMISSION_ADMIN_MANAGE_DEPARTMENTS = "admin.manage_departments"
PERMISSION_ADMIN_MANAGE_SETTINGS = "admin.manage_settings"
PERMISSION_ADMIN_MANAGE_WORKFLOWS = "admin.manage_workflows"
PERMISSION_ADMIN_VIEW_AUDIT_LOGS = "admin.view_audit_logs"
PERMISSION_SYSTEM_FULL_ACCESS = "system.full_access"

ROLE_PERMISSION_MAPPING = {
    ROLE_BRANCH_EMPLOYEE: {
        PERMISSION_ORDER_CREATE,
        PERMISSION_ORDER_VIEW_OWN,
        PERMISSION_ORDER_EDIT_DRAFT,
        PERMISSION_ORDER_CANCEL,
        PERMISSION_ORDER_DELIVER_BRANCH,
        PERMISSION_PAYMENT_COLLECT_BRANCH,
        PERMISSION_CASHBOX_VIEW_OWN,
    },
    ROLE_BRANCH_SUPERVISOR: {
        PERMISSION_ORDER_VIEW_BRANCH,
        PERMISSION_ORDER_CANCEL,
        PERMISSION_ORDER_APPROVE,
        PERMISSION_ORDER_REJECT,
        PERMISSION_ORDER_RETURN_FOR_EDIT,
        PERMISSION_ORDER_DELIVER_BRANCH,
        PERMISSION_FULFILLMENT_CREATE,
    },
    ROLE_DISTRIBUTION_MANAGER: {
        PERMISSION_FULFILLMENT_VIEW_QUEUE,
        PERMISSION_ORDER_CANCEL,
        PERMISSION_FULFILLMENT_SPLIT_BY_DEPARTMENT,
        PERMISSION_FULFILLMENT_CREATE_WORK_ORDERS,
        PERMISSION_FULFILLMENT_ASSIGN_DEPARTMENT,
        PERMISSION_FULFILLMENT_VIEW_DEPARTMENT_STATUS,
        PERMISSION_DELIVERY_BATCH_CREATE,
        PERMISSION_DELIVERY_BATCH_ASSIGN_DRIVER,
        PERMISSION_DELIVERY_BATCH_VIEW,
        PERMISSION_DELIVERY_VIEW_ALL,
    },
    ROLE_PRODUCTION_USER: {
        PERMISSION_WORK_ORDER_VIEW_DEPARTMENT,
        PERMISSION_WORK_ORDER_ACCEPT,
        PERMISSION_WORK_ORDER_REJECT,
        PERMISSION_WORK_ORDER_UPDATE_STATUS,
        PERMISSION_PRODUCTION_MARK_READY,
    },
    ROLE_DRIVER: {
        PERMISSION_DELIVERY_BATCH_VIEW_ASSIGNED,
        PERMISSION_DELIVERY_BATCH_UPDATE_STATUS,
        PERMISSION_DELIVERY_VIEW_ASSIGNED,
        PERMISSION_DELIVERY_UPDATE_STATUS,
        PERMISSION_DELIVERY_CONFIRM_DELIVERED,
        PERMISSION_DELIVERY_COLLECT_CASH,
        PERMISSION_CASHBOX_VIEW_OWN,
    },
    ROLE_CASHIER: {
        PERMISSION_CASHBOX_VIEW_ALL,
        PERMISSION_CASHBOX_REVIEW,
        PERMISSION_CASHBOX_APPROVE,
        PERMISSION_CASHBOX_RETURN,
        PERMISSION_CASHBOX_CLOSE_DAY,
    },
    ROLE_ACCOUNTANT: {
        PERMISSION_ACCOUNTING_VIEW_FINANCIALS,
        PERMISSION_ACCOUNTING_REVIEW_INVOICE,
        PERMISSION_ACCOUNTING_SUBMIT_INVOICE,
        PERMISSION_ACCOUNTING_REVIEW_PAYMENT,
        PERMISSION_ACCOUNTING_SUBMIT_PAYMENT,
        PERMISSION_ACCOUNTING_RECONCILE_PAYMENTS,
        PERMISSION_ACCOUNTING_VIEW_REPORTS,
        PERMISSION_ACCOUNTING_CLOSE_FINANCIAL_DAY,
    },
    ROLE_SYSTEM_ADMIN: {
        PERMISSION_SYSTEM_FULL_ACCESS,
        PERMISSION_ADMIN_MANAGE_USERS,
        PERMISSION_ADMIN_MANAGE_ROLES,
        PERMISSION_ADMIN_MANAGE_PERMISSIONS,
        PERMISSION_ADMIN_MANAGE_BRANCHES,
        PERMISSION_ADMIN_MANAGE_DEPARTMENTS,
        PERMISSION_ADMIN_MANAGE_SETTINGS,
        PERMISSION_ADMIN_MANAGE_WORKFLOWS,
        PERMISSION_ADMIN_VIEW_AUDIT_LOGS,
    },
}

ORDER_STATUS_DRAFT = "Draft"
ORDER_STATUS_PENDING_APPROVAL = "Pending Supervisor Approval"
ORDER_STATUS_RETURNED = "Returned For Edit"
ORDER_STATUS_REJECTED = "Rejected"
ORDER_STATUS_SENT_TO_DISTRIBUTION = "Sent To Distribution"
ORDER_STATUS_SENT_TO_PRODUCTION = "Sent To Production"
ORDER_STATUS_IN_PRODUCTION = "In Production"
ORDER_STATUS_PRODUCTION_COMPLETED = "Production Completed"
ORDER_STATUS_READY_FOR_PICKUP = "Ready For Pickup"
ORDER_STATUS_READY_FOR_DELIVERY = "Ready For Delivery"
ORDER_STATUS_ASSIGNED_TO_DRIVER = "Assigned To Driver"
ORDER_STATUS_DRIVER_PICKED_UP = "Driver Picked Up"
ORDER_STATUS_OUT_FOR_DELIVERY = "Out For Delivery"
ORDER_STATUS_DELIVERED = "Delivered"
ORDER_STATUS_DELIVERY_FAILED = "Delivery Failed"
ORDER_STATUS_CANCELLED = "Cancelled"

ORDER_STATUSES = [
    ORDER_STATUS_DRAFT,
    ORDER_STATUS_PENDING_APPROVAL,
    ORDER_STATUS_RETURNED,
    ORDER_STATUS_REJECTED,
    ORDER_STATUS_SENT_TO_DISTRIBUTION,
    ORDER_STATUS_SENT_TO_PRODUCTION,
    ORDER_STATUS_IN_PRODUCTION,
    ORDER_STATUS_PRODUCTION_COMPLETED,
    ORDER_STATUS_READY_FOR_PICKUP,
    ORDER_STATUS_READY_FOR_DELIVERY,
    ORDER_STATUS_ASSIGNED_TO_DRIVER,
    ORDER_STATUS_DRIVER_PICKED_UP,
    ORDER_STATUS_OUT_FOR_DELIVERY,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_DELIVERY_FAILED,
    ORDER_STATUS_CANCELLED,
]

ORDER_FLOW_STATUS_DRAFT = "draft"
ORDER_FLOW_STATUS_PENDING_APPROVAL = "pending_approval"
ORDER_FLOW_STATUS_APPROVED = "approved"
ORDER_FLOW_STATUS_IN_FULFILLMENT = "in_fulfillment"
ORDER_FLOW_STATUS_READY = "ready"
ORDER_FLOW_STATUS_DELIVERED = "delivered"
ORDER_FLOW_STATUS_COMPLETED = "completed"
ORDER_FLOW_STATUS_CANCELLED = "cancelled"
ORDER_FLOW_STATUS_REJECTED = "rejected"
ORDER_FLOW_STATUS_RETURNED_FOR_EDIT = "returned_for_edit"

ORDER_FLOW_STATUSES = [
    ORDER_FLOW_STATUS_DRAFT,
    ORDER_FLOW_STATUS_PENDING_APPROVAL,
    ORDER_FLOW_STATUS_APPROVED,
    ORDER_FLOW_STATUS_IN_FULFILLMENT,
    ORDER_FLOW_STATUS_READY,
    ORDER_FLOW_STATUS_DELIVERED,
    ORDER_FLOW_STATUS_COMPLETED,
    ORDER_FLOW_STATUS_CANCELLED,
    ORDER_FLOW_STATUS_REJECTED,
    ORDER_FLOW_STATUS_RETURNED_FOR_EDIT,
]

PRODUCTION_FLOW_STATUS_NOT_STARTED = "not_started"
PRODUCTION_FLOW_STATUS_SPLIT_BY_DEPARTMENT = "split_by_department"
PRODUCTION_FLOW_STATUS_WORK_ORDERS_CREATED = "department_work_orders_created"
PRODUCTION_FLOW_STATUS_IN_PRODUCTION = "in_production"
PRODUCTION_FLOW_STATUS_PARTIALLY_READY = "partially_ready"
PRODUCTION_FLOW_STATUS_READY = "ready"
PRODUCTION_FLOW_STATUS_DELAYED = "delayed"
PRODUCTION_FLOW_STATUS_REJECTED = "rejected"

PRODUCTION_FLOW_STATUSES = [
    PRODUCTION_FLOW_STATUS_NOT_STARTED,
    PRODUCTION_FLOW_STATUS_SPLIT_BY_DEPARTMENT,
    PRODUCTION_FLOW_STATUS_WORK_ORDERS_CREATED,
    PRODUCTION_FLOW_STATUS_IN_PRODUCTION,
    PRODUCTION_FLOW_STATUS_PARTIALLY_READY,
    PRODUCTION_FLOW_STATUS_READY,
    PRODUCTION_FLOW_STATUS_DELAYED,
    PRODUCTION_FLOW_STATUS_REJECTED,
]

DELIVERY_FLOW_STATUS_NOT_REQUIRED = "not_required"
DELIVERY_FLOW_STATUS_WAITING_BATCH = "waiting_batch"
DELIVERY_FLOW_STATUS_ADDED_TO_BATCH = "added_to_delivery_batch"
DELIVERY_FLOW_STATUS_ASSIGNED_TO_DRIVER = "assigned_to_driver"
DELIVERY_FLOW_STATUS_PICKED_UP = "picked_up"
DELIVERY_FLOW_STATUS_OUT_FOR_DELIVERY = "out_for_delivery"
DELIVERY_FLOW_STATUS_DELIVERED = "delivered"
DELIVERY_FLOW_STATUS_PARTIALLY_DELIVERED = "partially_delivered"
DELIVERY_FLOW_STATUS_RETURNED = "returned"

DELIVERY_FLOW_STATUSES = [
    DELIVERY_FLOW_STATUS_NOT_REQUIRED,
    DELIVERY_FLOW_STATUS_WAITING_BATCH,
    DELIVERY_FLOW_STATUS_ADDED_TO_BATCH,
    DELIVERY_FLOW_STATUS_ASSIGNED_TO_DRIVER,
    DELIVERY_FLOW_STATUS_PICKED_UP,
    DELIVERY_FLOW_STATUS_OUT_FOR_DELIVERY,
    DELIVERY_FLOW_STATUS_DELIVERED,
    DELIVERY_FLOW_STATUS_PARTIALLY_DELIVERED,
    DELIVERY_FLOW_STATUS_RETURNED,
]

ORDER_PAYMENT_FLOW_STATUS_UNPAID = "unpaid"
ORDER_PAYMENT_FLOW_STATUS_PARTIALLY_PAID = "partially_paid"
ORDER_PAYMENT_FLOW_STATUS_PAID = "paid"
ORDER_PAYMENT_FLOW_STATUS_CASH_PENDING = "cash_pending"
ORDER_PAYMENT_FLOW_STATUS_CASH_CLOSED = "cash_closed"
ORDER_PAYMENT_FLOW_STATUS_REFUNDED = "refunded"

ORDER_PAYMENT_FLOW_STATUSES = [
    ORDER_PAYMENT_FLOW_STATUS_UNPAID,
    ORDER_PAYMENT_FLOW_STATUS_PARTIALLY_PAID,
    ORDER_PAYMENT_FLOW_STATUS_PAID,
    ORDER_PAYMENT_FLOW_STATUS_CASH_PENDING,
    ORDER_PAYMENT_FLOW_STATUS_CASH_CLOSED,
    ORDER_PAYMENT_FLOW_STATUS_REFUNDED,
]

ACCOUNTING_FLOW_STATUS_NOT_POSTED = "not_posted"
ACCOUNTING_FLOW_STATUS_SALES_ORDER_CREATED = "sales_order_created"
ACCOUNTING_FLOW_STATUS_DRAFT_INVOICE_CREATED = "draft_invoice_created"
ACCOUNTING_FLOW_STATUS_INVOICE_SUBMITTED = "invoice_submitted"
ACCOUNTING_FLOW_STATUS_PAYMENT_SUBMITTED = "payment_submitted"
ACCOUNTING_FLOW_STATUS_ACCOUNTING_POSTED = "accounting_posted"

ACCOUNTING_FLOW_STATUSES = [
    ACCOUNTING_FLOW_STATUS_NOT_POSTED,
    ACCOUNTING_FLOW_STATUS_SALES_ORDER_CREATED,
    ACCOUNTING_FLOW_STATUS_DRAFT_INVOICE_CREATED,
    ACCOUNTING_FLOW_STATUS_INVOICE_SUBMITTED,
    ACCOUNTING_FLOW_STATUS_PAYMENT_SUBMITTED,
    ACCOUNTING_FLOW_STATUS_ACCOUNTING_POSTED,
]

DEPARTMENT_WORK_ORDER_STATUS_PENDING = "pending"
DEPARTMENT_WORK_ORDER_STATUS_ACCEPTED = "accepted"
DEPARTMENT_WORK_ORDER_STATUS_IN_PRODUCTION = "in_production"
DEPARTMENT_WORK_ORDER_STATUS_DELAYED = "delayed"
DEPARTMENT_WORK_ORDER_STATUS_READY = "ready"
DEPARTMENT_WORK_ORDER_STATUS_REJECTED = "rejected"
DEPARTMENT_WORK_ORDER_STATUS_CANCELLED = "cancelled"

DEPARTMENT_WORK_ORDER_STATUSES = [
    DEPARTMENT_WORK_ORDER_STATUS_PENDING,
    DEPARTMENT_WORK_ORDER_STATUS_ACCEPTED,
    DEPARTMENT_WORK_ORDER_STATUS_IN_PRODUCTION,
    DEPARTMENT_WORK_ORDER_STATUS_DELAYED,
    DEPARTMENT_WORK_ORDER_STATUS_READY,
    DEPARTMENT_WORK_ORDER_STATUS_REJECTED,
    DEPARTMENT_WORK_ORDER_STATUS_CANCELLED,
]

DELIVERY_BATCH_STATUS_PENDING = "pending"
DELIVERY_BATCH_STATUS_DRAFT = "draft"
DELIVERY_BATCH_STATUS_ASSIGNED = "assigned"
DELIVERY_BATCH_STATUS_PICKED_UP = "picked_up"
DELIVERY_BATCH_STATUS_OUT_FOR_DELIVERY = "out_for_delivery"
DELIVERY_BATCH_STATUS_DELIVERED = "delivered"
DELIVERY_BATCH_STATUS_PARTIALLY_DELIVERED = "partially_delivered"
DELIVERY_BATCH_STATUS_RETURNED = "returned"
DELIVERY_BATCH_STATUS_CANCELLED = "cancelled"

DELIVERY_BATCH_STATUSES = [
    DELIVERY_BATCH_STATUS_PENDING,
    DELIVERY_BATCH_STATUS_DRAFT,
    DELIVERY_BATCH_STATUS_ASSIGNED,
    DELIVERY_BATCH_STATUS_PICKED_UP,
    DELIVERY_BATCH_STATUS_OUT_FOR_DELIVERY,
    DELIVERY_BATCH_STATUS_DELIVERED,
    DELIVERY_BATCH_STATUS_PARTIALLY_DELIVERED,
    DELIVERY_BATCH_STATUS_RETURNED,
    DELIVERY_BATCH_STATUS_CANCELLED,
]

DELIVERY_BATCH_OPEN_STATUSES = [
    DELIVERY_BATCH_STATUS_PENDING,
    DELIVERY_BATCH_STATUS_DRAFT,
]

ORDER_PRIORITY_NORMAL = "normal"
ORDER_PRIORITY_URGENT = "urgent"
ORDER_PRIORITY_VIP = "vip"
ORDER_PRIORITY_SCHEDULED = "scheduled"

ORDER_PRIORITIES = [
    ORDER_PRIORITY_NORMAL,
    ORDER_PRIORITY_URGENT,
    ORDER_PRIORITY_VIP,
    ORDER_PRIORITY_SCHEDULED,
]

EXCEPTION_REASON_CATEGORY_PRODUCTION = "production"
EXCEPTION_REASON_CATEGORY_DELIVERY = "delivery"
EXCEPTION_REASON_CATEGORY_PAYMENT = "payment"
EXCEPTION_REASON_CATEGORY_CUSTOMER = "customer"

EXCEPTION_REASON_CATEGORIES = [
    EXCEPTION_REASON_CATEGORY_PRODUCTION,
    EXCEPTION_REASON_CATEGORY_DELIVERY,
    EXCEPTION_REASON_CATEGORY_PAYMENT,
    EXCEPTION_REASON_CATEGORY_CUSTOMER,
]

EXCEPTION_REASONS = {
    EXCEPTION_REASON_CATEGORY_PRODUCTION: [
        {
            "code": "item_unavailable",
            "label": "الصنف غير متوفر",
            "description": "يستخدم عند عدم توفر منتج أو مكون مطلوب للتنفيذ.",
        },
        {
            "code": "delayed_production",
            "label": "تأخير في الإنتاج",
            "description": "يستخدم عند وجود تأخير تشغيلي في جهة التنفيذ.",
        },
        {
            "code": "capacity_full",
            "label": "الطاقة التشغيلية ممتلئة",
            "description": "يستخدم عندما لا تستطيع جهة التنفيذ قبول المزيد من الطلبات.",
        },
        {
            "code": "quality_issue",
            "label": "ملاحظة جودة",
            "description": "يستخدم عند وجود مشكلة جودة تحتاج مراجعة قبل التسليم.",
        },
    ],
    EXCEPTION_REASON_CATEGORY_DELIVERY: [
        {
            "code": "driver_issue",
            "label": "مشكلة لدى السائق",
            "description": "يستخدم عند وجود عائق يمنع السائق من إكمال المسار.",
        },
        {
            "code": "branch_closed",
            "label": "الفرع مغلق",
            "description": "يستخدم عند تعذر الاستلام أو التسليم بسبب إغلاق الفرع.",
        },
        {
            "code": "damaged_item",
            "label": "تلف في الطلب",
            "description": "يستخدم عند تلف الطلب قبل أو أثناء التوصيل.",
        },
        {
            "code": "delivery_failed",
            "label": "تعذر التوصيل",
            "description": "يستخدم عند فشل محاولة التوصيل للعميل.",
        },
    ],
    EXCEPTION_REASON_CATEGORY_PAYMENT: [
        {
            "code": "payment_failed",
            "label": "فشل عملية الدفع",
            "description": "يستخدم عند تعذر إتمام عملية الدفع أو التحصيل.",
        },
        {
            "code": "cash_difference",
            "label": "فرق في العهدة",
            "description": "يستخدم عند وجود فرق بين المبلغ المسجل والمستلم.",
        },
        {
            "code": "unpaid_amount",
            "label": "مبلغ متبق غير مسدد",
            "description": "يستخدم عندما يمنع المتبقي غير المسدد إتمام التسليم.",
        },
    ],
    EXCEPTION_REASON_CATEGORY_CUSTOMER: [
        {
            "code": "customer_cancelled",
            "label": "إلغاء من العميل",
            "description": "يستخدم عند طلب العميل إلغاء الطلب.",
        },
        {
            "code": "customer_not_available",
            "label": "تعذر الوصول للعميل",
            "description": "يستخدم عند عدم تجاوب العميل أو عدم وجوده في الموقع.",
        },
        {
            "code": "customer_requested_change",
            "label": "طلب تعديل من العميل",
            "description": "يستخدم عندما يطلب العميل تعديل تفاصيل الطلب.",
        },
    ],
}

PACKING_STATUS_NOT_REQUIRED = "not_required"
PACKING_STATUS_WAITING = "waiting"
PACKING_STATUS_READY_FOR_PACKING = "ready_for_packing"
PACKING_STATUS_PACKED = "packed"
PACKING_STATUS_READY = "ready"

PACKING_STATUSES = [
    PACKING_STATUS_NOT_REQUIRED,
    PACKING_STATUS_WAITING,
    PACKING_STATUS_READY_FOR_PACKING,
    PACKING_STATUS_PACKED,
    PACKING_STATUS_READY,
]

PAYMENT_STATUS_RECORDED = "Recorded By Employee"
PAYMENT_STATUS_IN_DAILY_CLOSURE = "In Daily Closure"
PAYMENT_STATUS_SUBMITTED = "Submitted To Cashier"
PAYMENT_STATUS_RETURNED = "Returned For Review"
PAYMENT_STATUS_CASHIER_ACCEPTED = "Cashier Accepted"
PAYMENT_STATUS_READY_FOR_ERP = "Ready For ERPNext Posting"
PAYMENT_STATUS_POSTED_TO_ERP = "Posted To ERPNext"
PAYMENT_STATUS_LINKED_TO_INVOICE = "Linked To Invoice"

PAYMENT_STATUSES = [
    PAYMENT_STATUS_RECORDED,
    PAYMENT_STATUS_IN_DAILY_CLOSURE,
    PAYMENT_STATUS_SUBMITTED,
    PAYMENT_STATUS_RETURNED,
    PAYMENT_STATUS_CASHIER_ACCEPTED,
    PAYMENT_STATUS_READY_FOR_ERP,
    PAYMENT_STATUS_POSTED_TO_ERP,
    PAYMENT_STATUS_LINKED_TO_INVOICE,
]

CLOSURE_STATUS_OPEN = "Open"
CLOSURE_STATUS_SUBMITTED = "Submitted To Cashier"
CLOSURE_STATUS_RETURNED = "Returned For Review"
CLOSURE_STATUS_ACCEPTED = "Accepted"
CLOSURE_STATUS_CLOSED = "Closed"
CLOSURE_STATUS_HAS_DIFFERENCE = "Has Difference"

CLOSURE_STATUSES = [
    CLOSURE_STATUS_OPEN,
    CLOSURE_STATUS_SUBMITTED,
    CLOSURE_STATUS_RETURNED,
    CLOSURE_STATUS_ACCEPTED,
    CLOSURE_STATUS_CLOSED,
    CLOSURE_STATUS_HAS_DIFFERENCE,
]

ERP_SYNC_NOT_SYNCED = "Not Synced"
ERP_SYNC_PENDING = "Pending"
ERP_SYNC_SYNCED = "Synced"
ERP_SYNC_FAILED = "Failed"
ERP_SYNC_PARTIALLY_SYNCED = "Partially Synced"

ERP_SYNC_STATUSES = [
    ERP_SYNC_NOT_SYNCED,
    ERP_SYNC_PENDING,
    ERP_SYNC_SYNCED,
    ERP_SYNC_FAILED,
    ERP_SYNC_PARTIALLY_SYNCED,
]
